;===============================================================================
;fileio.inc
;===============================================================================
;define some constants for the file.asm, also to include them in other asm files
;-------------------------------------------------------------------------------

;FILE struct constants
FILE_DATA equ 0
FILE_SIZE equ 4

;PAK file constants
PAK_ID equ 0
PAK_FILETABLE equ 4
PAK_FILETABLESIZE equ 8



